### ISSUE TITLE
Undocumented methods

### ISSUE THREAD

**Issue by christophergandrud** [IQSS/ZeligChoice#19]
`bbinchoice` and `obinchoice`appear to be undocumented on http://docs.zeligproject.org/en/latest/index.html

**Comment by tercer** [comment]
They are only ever inherited, never called themselves, so they have no examples to document.

https://github.com/IQSS/ZeligChoice/blob/master/R/model-obinchoice.R#L1
https://github.com/IQSS/ZeligChoice/blob/master/R/model-bbinchoice.R#L1

<img width="502" alt="screen shot 2017-05-02 at 12 56 45 pm" src="https://cloud.githubusercontent.com/assets/2085037/25629237/dce5f1c0-2f36-11e7-9cfe-d326eb575d25.png">

**Comment by christophergandrud** [comment]
Thanks for the info. I'll add on stubs, mentioning this
