### ISSUE TITLE
Mlogit model

### ISSUE THREAD

**Issue by cchoirat** [IQSS/ZeligChoice#5]

**Comment by tercer** [comment]
As a review/update, the wrapper works, setx() gives a warning, but works, sim() works.  However, there is no plot() method that works on the qi's generated by sim().

**Comment by tercer** [comment]
Plot method created for categorical outcomes, such as result from mlogit.  Added to core Zelig and used in ZeligChoice.  For example:

![screen shot 2015-11-20 at 5 14 28 pm](https://cloud.githubusercontent.com/assets/2085037/11313345/365d4f74-8faa-11e5-86f1-021e0d7cb1ca.png)
